name: Compiles the Compiler

on: [push]

jobs:
  compiles:
    name: "Runs `make compile`"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: make compile
  parts:
    name: "Grades assignment"
    runs-on: ubuntu-latest
    needs: [compiles]
    strategy:
      matrix:
        part: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    steps:
      - name: "Downloads grader scripts"
        uses: actions/checkout@master
        with:
          repository: utah-cs4470-sp23/grader
          path: grader
      - name: "Counts total parts"
        runs: echo "HW_PARTS=$(make -C grader count-current)" >> $GITHUB_ENV
      - name: Grade part ${{ env.HW_PARTS }}
        if: matrix.part <= env.HW_PARTS
        timeout-minutes: 5
        runs: make -C grader test-current DIR=$GITHUB_WORKSPACE PART=${{ matrix.part }}

